name: archioweb-qimg

services:
  app:
    build:
      context: .
    image: archioweb/qimg
    depends_on:
      - db
    environment:
      DEBUG: qimg:*
      QIMG_ADMIN_TOKEN:
      QIMG_BASE_URL:
      QIMG_DATABASE_URL: postgresql://qimg:${QIMG_DATABASE_PASSWORD}@db/qimg
      QIMG_IMAGE_MAX_SIZE:
      QIMG_IMAGE_QUOTA:
    init: true
    networks:
      - app
      - db
    ports:
      - '${QIMG_PORT:-3000}:3000'
    restart: on-failure

  db:
    image: postgres:17.2-alpine
    environment:
      POSTGRES_PASSWORD: ${QIMG_DATABASE_PASSWORD}
      POSTGRES_USER: qimg
      POSTGRES_DB: qimg
    networks:
      - db
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  app:
  db:

volumes:
  db-data:
